// Code generated by mockery. DO NOT EDIT.

package health

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MetricWriter is an autogenerated mock type for the MetricWriter type
type MetricWriter struct {
	mock.Mock
}

// Peers provides a mock function with given fields: _a0, _a1
func (_m *MetricWriter) Peers(_a0 context.Context, _a1 uint64) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
