// Code generated by mockery. DO NOT EDIT.

package health

import mock "github.com/stretchr/testify/mock"

// Notifier is an autogenerated mock type for the Notifier type
type Notifier struct {
	mock.Mock
}

// Alert provides a mock function with given fields: message
func (_m *Notifier) Alert(message string) {
	_m.Called(message)
}

// Info provides a mock function with given fields: message
func (_m *Notifier) Info(message string) {
	_m.Called(message)
}

// Status provides a mock function with given fields: message
func (_m *Notifier) Status(message string) {
	_m.Called(message)
}
